services:
  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    networks:
      - backend_net
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: mypassword
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    build:
      context: ./DevOps/database/
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_net

  redis:
    image: redis:7.4
    command: redis-server --requirepass mypassword
    networks:
      - backend_net

  nginx:
    build:
      context: ./DevOps/nginx/
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
    networks:
      - backend_net
    depends_on:
    - backend

networks:
  backend_net:

volumes:
  postgres_data:
